[build-system]
requires = ["setuptools>=61.2.0", "poetry-core", "wheel", "setuptools_scm[toml]>=7.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]

[tool.poetry]
name = "codes-pypo"
version = "1.0"
description = "Python-based process operability package"
authors = ["Victor Alves"]
license = "MIT License"
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering/Process Systems Engineering",
]
packages = [{ include = "pypo.py", from = "src" },
			{include =   "PolyhedraVolAprox.py", from="src"}]
exclude = ["*.tests", "*.tests.*", "tests.*", "tests", "*.obsolete", "*.obsolete.*", "obsolete.*", "obsolete", "*.Experimental", "*.Experimental.*", "Experimental.*", "Experimental", "*.docs", "*.docs.*", "docs.*", "docs"]

[tool.poetry.dependencies]
python = "^3.9.0"
numpy = "^1.24.1"
scipy = "^1.10.0"
tqdm = "^4.64.1"
matplotlib = "^3.6.2"
polytope = {git = "https://github.com/tulip-control/polytope.git", branch = "main"}
jax = {extras = ["cpu"], version = "^0.4.0"}
cvxopt = "^1.2.7"

